services:
  redis:
    container_name: todo-turbo-redis
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  backend:
    environment:
      TODOTURBO_REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      TODOTURBO_REDIS_PORT: ${REDIS_PORT}
    restart: on-failure
    depends_on:
      - redis
    container_name: todo-turbo-backend
    build: .
    ports:
      - "8080:8080"

volumes:
  redis-data: